### API PLANO - GET
GET http://localhost:8080/api/v1/planos

### API PLANO - POST
POST http://localhost:8080/api/v1/planos
Content-Type: application/json

{
    "nomePlano": "roberto",
    "beneficios": "roberto@gmail.com",
    "preco": "2.5"
}

### API PLANO - PUT
PUT http://localhost:8080/api/v1/planos/2
Content-Type: application/json

{
    "nomePlano": "roberto_novo",
    "beneficios": "roberto@gmail.com",
    "preco": "5.75"
}

### API PLANO - DELETE
DELETE http://localhost:8080/api/v1/planos/2
Content-Type: application/json