### API RECRUTADOR - GET
GET http://localhost:8080/api/v1/recrutadores

### API RECRUTADOR - POST
POST http://localhost:8080/api/v1/recrutadores
Content-Type: application/json

{
    "nome": "roberto",
    "nomeEmpresa": "roberto@gmail.com"
}

### API RECRUTADOR - PUT
PUT http://localhost:8080/api/v1/recrutadores/1
Content-Type: application/json

{
    "nome": "roberto_novo",
    "nomeEmpresa": "roberto@gmail.com"
}

### API RECRUTADOR - DELETE
DELETE http://localhost:8080/api/v1/recrutadores/1
Content-Type: application/json