### API USUARIO - GET
GET http://localhost:8080/api/v1/usuarios

### API USUARIO - POST
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
    "nome": "roberto_novo",
    "email": "roberto@gmail.com",
    "historicoProfissional": "não tenho histórico",
    "qualificacoes": "lalalala",
    "areasDeInteresse": "todas as areas"
}

### API USUARIO - PUT
PUT http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json

{
    "nome": "roberto_novo",
    "email": "roberto@gmail.com",
    "historicoProfissional": "não tenho histórico",
    "qualificacoes": "lalalala",
    "areasDeInteresse": "todas as areas"
}

### API USUARIO - DELETE
DELETE http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json